# Site settings
title: Hi, I'm Nadia
email: deatsukuba@gmail.com
url: ''
description: "Hi! I'm a geospatial data analyst and map maker exploring earth through maps, code, and everything in between (and beyond)! I live and work in Indonesia"
skills: "Hi! I'm a geospatial data analyst and map maker exploring earth through maps, code, and everything in between (and beyond)! I live and work in Indonesia"

meta_author: ''

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
